/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Crate(props) {
	const { nodes, materials } = useGLTF("/models/Crate.glb");
	// const crateRef = useRef();
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.crate.geometry}
				material={materials.restaurant}
				scale={100}
			/>
		</group>
	);
}

useGLTF.preload("/models/Crate.glb");
