/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function RockMed(props) {
	const { nodes, materials } = useGLTF("/models/RockMed3.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock_Medium_2.geometry}
				material={materials.Rocks}
			/>
		</group>
	);
}

useGLTF.preload("/models/RockMed3.glb");
