/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Bee(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/Armabee.glb");
	const { actions } = useAnimations(animations, group);
	console.log("Actions: ", actions);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.Root} />
					</group>
					<group name='Armabee' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<skinnedMesh
							name='Armabee_1'
							geometry={nodes.Armabee_1.geometry}
							material={materials.Armabee_Main}
							skeleton={nodes.Armabee_1.skeleton}
						/>
						<skinnedMesh
							name='Armabee_2'
							geometry={nodes.Armabee_2.geometry}
							material={materials.Armabee_Secondary}
							skeleton={nodes.Armabee_2.skeleton}
						/>
						<skinnedMesh
							name='Armabee_3'
							geometry={nodes.Armabee_3.geometry}
							material={materials.Eye_White}
							skeleton={nodes.Armabee_3.skeleton}
						/>
						<skinnedMesh
							name='Armabee_4'
							geometry={nodes.Armabee_4.geometry}
							material={materials.Eye_Black}
							skeleton={nodes.Armabee_4.skeleton}
						/>
						<skinnedMesh
							name='Armabee_5'
							geometry={nodes.Armabee_5.geometry}
							material={materials.Wings}
							skeleton={nodes.Armabee_5.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/Armabee.glb");
