/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Panda(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/Panda.glb");
	const { actions } = useAnimations(animations, group);
	console.log("Panda actions; ", actions);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.Root} />
					</group>
					<skinnedMesh
						name='Headband'
						geometry={nodes.Headband.geometry}
						material={materials.AtlasMaterial}
						skeleton={nodes.Headband.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={150}
					/>
					<skinnedMesh
						name='Panda'
						geometry={nodes.Panda.geometry}
						material={materials.AtlasMaterial}
						skeleton={nodes.Panda.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={150}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/Panda.glb");
