/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Clover(props) {
	const { nodes, materials } = useGLTF("/models/Clover.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Clover_2.geometry}
				material={materials.Leaves}
			/>
		</group>
	);
}

useGLTF.preload("/models/Clover.glb");
