/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function Fern(props) {
	const { nodes, materials } = useGLTF("/models/Fern.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Fern_1.geometry}
				material={materials.Leaves}
			/>
		</group>
	);
}

useGLTF.preload("/models/Fern.glb");
