/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function Mushrooms(props) {
	const { nodes, materials } = useGLTF("/models/Mushroom.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Mushroom_Common.geometry}
				material={materials.Mushrooms}
			/>
		</group>
	);
}

useGLTF.preload("/models/Mushroom.glb");
