/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pine(props) {
	const { nodes, materials } = useGLTF("/models/Pine.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Pine_4_1.geometry}
				material={materials.Bark_NormalTree}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Pine_4_2.geometry}
				material={materials.Leaves_Pine}
			/>
		</group>
	);
}

useGLTF.preload("/models/Pine.glb");
